# ./docker-compose.yml

version: '3.9'

services:
  fastapi:
    build: .
    container_name: JamJam-fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped